In [16]:
import numpy as np

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

<center><b><h1>Indexing</h1></b></center>

In [26]:
# number from the 2nd row and 3rd column
A[1, 2]

np.int64(6)

<center><h1>Slicing</h1></center>

In [27]:
# from row 0 to 3 and from the 2nd column to the end
A[0:3, -2:]
# or A[0:3, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
B = np.zeros((4, 4))

In [28]:
# all numbers from the 2nd to the 2nd-to-last row and from the 2nd to the 2nd-to-last column
B[1:-1, 1:-1] = 1
# or B[1:3, 1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [ ]:
C = np.zeros((5, 5))

In [29]:
# all rows and columns with a step of 2
C[::2, ::2] = 1
# or C[1::2, 1::2] = 1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [23]:
D = np.random.randint(0, 10, [5, 5])

In [30]:
# all numbers in D smaller than 5
D[D<5]

array([3, 3, 1, 1, 4, 3, 1, 0, 4, 3, 2])