In [24]:
import numpy as np

**<center>Initialisation</center>**

In [34]:
# a table with 4 rows and 5 columns filled with 3
A = np.full((4, 5), 3)
A

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [35]:
# a table with 4 rows and 5 columns filled with 1
B = np.ones((4, 5))
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# a table with 4 rows and 5 columns filled with 0
C = np.zeros((4, 5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**<center>plages</center>**

In [37]:
# a table with numbers from 0 to 10 with a step of 2
X = np.arange(0, 10, 2)
X

array([0, 2, 4, 6, 8])

In [38]:
# a table with 5 numbers between 0 and 10
Y = np.linspace(0, 10, 5)
Y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**<center>array manipulation</center>**

In [39]:
# put A and B together
D = np.concatenate((A, B), axis=0)
D

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# put A and B together the other way
E = np.concatenate((A, B), axis=1)
E

array([[3., 3., 3., 3., 3., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 1., 1., 1., 1., 1.]])

In [41]:
# make E flat into 1 line
F = E.ravel()
F

array([3., 3., 3., 3., 3., 1., 1., 1., 1., 1., 3., 3., 3., 3., 3., 1., 1.,
       1., 1., 1., 3., 3., 3., 3., 3., 1., 1., 1., 1., 1., 3., 3., 3., 3.,
       3., 1., 1., 1., 1., 1.])

In [42]:
# change F's size
G = F.reshape(8, 5)
G

array([[3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.]])