In [6]:
import numpy as np

In [7]:
# @title
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [8]:
a = A.sum(axis=0)
b = A.sum(axis=1)
a, b

(array([ 8,  7, 12]), array([ 8, 19]))

In [9]:
A.var()

np.float64(8.583333333333334)

In [10]:
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [13]:
np.corrcoef(A)[0, 1]

np.float64(-0.56)

In [16]:
values, counts = np.unique(A, return_counts=True)

In [19]:
values[counts.argsort()], counts[counts.argsort()]

(array([0, 5, 7, 9, 3]), array([1, 1, 1, 1, 2]))

In [22]:
np.nancumsum(A, axis=1)

array([[ 5,  5,  8],
       [ 3, 10, 19]])

In [23]:
np.isnan(A).sum()

np.int64(0)

In [26]:
np.isnan(A).sum()/A.size

np.float64(0.0)

In [27]:
image = np.array([[0, 2, 18, 1, 0],
                  [1, 15, 20, 14, 2],
                  [19, 3, 1, 17, 1],
                  [2, 16, 18, 15, 0],
                  [0, 1, 19, 2, 1]])

In [28]:
image.mean()

np.float64(7.52)

In [32]:
image[image > 10]

array([18, 15, 20, 14, 19, 17, 16, 18, 15, 19])

In [31]:
image[image < 10] = 0
image

array([[ 0,  0, 18,  0,  0],
       [ 0, 15, 20, 14,  0],
       [19,  0,  0, 17,  0],
       [ 0, 16, 18, 15,  0],
       [ 0,  0, 19,  0,  0]])